### PR TITLE
Feature: Configurable asset containers & choice overriding

### PR DESCRIPTION
**Pull request by quintenbuis**
This PR adds the ability to configure the asset containers that need to be cleared and allows overriding of choice in the command for automation purposes.

### CODE REVIEW

**Comment by quintenbuis** [comment]
Fixes #7

**Comment by quintenbuis** [comment]
@aozisik Are you planning on merging this PR? Would love to see these changes in the project.

**Comment by aozisik** [comment]
Hi @quintenbuis,

Thank you for your PR. Yes, we want to include your changes. At least functionality wise, if it's not directly merging it. We have something similar cooking over here, which is a bit more complex. Have a look: #8  No clear ETA yet, but it's coming soon 👍

**Comment by quintenbuis** [comment]
@aozisik Ok! I've got another feature lined up to go after this one. Maybe you could also implement it. Please tak e a look at the following commit i've made: https://github.com/quintenbuis/statamic-clear-assets/commit/984492ea18383c45c34e236faf64982d38013673.

**Comment by aozisik** [comment]
Handled in #8 .

Thank you @quintenbuis !

**Pull request closed without merging**
